window.learnArticles = [
  {id:"mindfulness",title:"Mindfulness interventions for anxiety and depression",source:"Clinical Psychology Review · PubMed",category:"Mental Wellness",minutes:23,published:"7 Jan 2026",icon:"fa-solid fa-brain",url:"https://pubmed.ncbi.nlm.nih.gov/41512699/",excerpt:"A 2026 systematic review and meta-analysis of mindfulness interventions for anxiety and depression. It brings together current clinical evidence while recognising differences between study designs.",notes:[]},
  {id:"nutrition",title:"Dietary fat: know which to choose",source:"Mayo Clinic",category:"Nutrition",minutes:18,published:"16 Apr 2026",icon:"fa-solid fa-apple-whole",url:"https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/in-depth/fat/art-20045550",excerpt:"A practical 2026 overview of dietary fats and the food sources that supply them. It explains why overall dietary patterns matter more than viewing a single nutrient in isolation.",notes:[]},
  {id:"sleep",title:"Sleep health and sleep disorders: a two-continua model",source:"Sleep Medicine Reviews · PubMed",category:"Sleep",minutes:16,published:"13 Jul 2026",icon:"fa-solid fa-moon",url:"https://pubmed.ncbi.nlm.nih.gov/42468242/",excerpt:"A 2026 review on considering sleep health alongside sleep disorders. It explores quality, timing, regularity and daytime function as part of a broader clinical picture.",notes:[]},
  {id:"fitness",title:"Physical activity and mental health across life domains",source:"British Journal of Sports Medicine · PubMed",category:"Fitness",minutes:24,published:"12 Feb 2026",icon:"fa-solid fa-person-running",url:"https://pubmed.ncbi.nlm.nih.gov/40903203/",excerpt:"An updated systematic review and meta-analysis spanning 3.3 million people. It considers how activity in different settings relates to mental-health outcomes.",notes:[]},
  {id:"cancer",title:"Global cancer prevention: current approaches and future directions",source:"ASCO Educational Book · PubMed",category:"Cancer",minutes:31,published:"26 May 2026",icon:"fa-solid fa-ribbon",url:"https://pubmed.ncbi.nlm.nih.gov/42190157/",excerpt:"A 2026 education-session synthesis of prevention, vaccination and screening. It connects established modifiable risks with current approaches to equitable cancer control.",notes:[]},
  {id:"clotting",title:"Thrombosis at the crossroads of inflammation and coagulation",source:"Clinica Chimica Acta · PubMed",category:"Clotting",minutes:26,published:"7 May 2026",icon:"fa-solid fa-droplet",url:"https://pubmed.ncbi.nlm.nih.gov/42105941/",excerpt:"A Mayo Clinic–affiliated review of thrombosis and vascular biology. It brings inflammation, coagulation and vascular processes together in one current overview.",notes:[]},
  {id:"research",title:"Sleep EEG foundation models and health screening",source:"npj Digital Medicine · PubMed",category:"Research",minutes:20,published:"9 Jul 2026",icon:"fa-solid fa-flask",url:"https://pubmed.ncbi.nlm.nih.gov/42426257/",excerpt:"Johns Hopkins–affiliated 2026 research on sleep EEG and health screening. It explores whether detailed sleep-stage signals can improve screening beyond standard staging.",notes:[]},
  {id:"prevention",title:"Healthy-diet advice for cardiovascular secondary prevention",source:"British Journal of General Practice · PubMed",category:"Prevention",minutes:22,published:"14 May 2026",icon:"fa-solid fa-shield-heart",url:"https://pubmed.ncbi.nlm.nih.gov/42134945/",excerpt:"A systematic review and meta-analysis on dietary advice in general practice. It focuses on the role of healthy dietary patterns in people with established cardiovascular disease.",notes:[]}
];
